name: Test

on:
  push:
    branches: [ master, ci ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mkchlog
        uses: actions/checkout@v2
      - name: Checkout toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Test mkchlog
        run: cargo test
